Sample of detected bugs
Bug 1: Uncaught Exception (see attached files: bug01.test, bug01.py)
Attempting to delete a Node from a Tree that does not contain that Node results in an undefined
global name error. ERROR: (<type 'exceptions.NameError'>, NameError("global name 'root' is
not defined",), <traceback object at 0x0364D4E0>)

Bug 2: Infinite Loop (see attached files: bug02.test, bug02.py)
This bug is a result of trying to insert a Node into a Tree from which is already belongs.

Bug 3: Uncaught Exception (see attached files: bug03.test, bug03.py)
Call to black_height() results in a Node instance has no attribute error. Specifically the ‘is_black’
attribute is absent.

Bug 4: Type Error (see attached files: bug04.test, bug04.py)
This bug is a result of using raise without providing an exception type or instance.
raise "x.right is nil!"
TypeError: exceptions must be old-style classes or derived from BaseException, not str